name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: GitHub Action for Firebase
      uses: w9jds/firebase-action@v1.0
    - name: Install
      run: npm install && npm run build
    - name: Deploy
      with: # Set the secret as an input
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase deploy --token $FIREBASE_TOKEN
