name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Install Dependencies
      run: npm install
    - name: Build b185...
      run: npm run build
    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@v1.0
      with:
        args: deploy --only hosting:demo --project abe-today
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: abe-today 
